version: "3.9"

services:
  test:
    network_mode: host
    image: golang:1.19
    environment:
      C4_SERVICE_NAME: logs
      GOPRIVATE: bitbucket.org
    working_dir: /code
    volumes:
      - ./:/code
    command: sh -c "apt-get update -y && go test -v -coverpkg=./... -coverprofile=cover.out ./..."
